import { z } from "zod";

/**
 * Schema for validating assignment documents before saving to Firestore.
 * assignment_id is generated by Firestore and is not part of the validated payload.
 */
export const AssignmentSchema = z.object({
  case_id: z.string().min(1, "Case ID is required"),
  user_id: z.string().min(1, "User ID is required"),
  user_name: z.string().optional(),
  assigned_by: z.string().min(1, "Assigned by is required"),

  required_equipment: z.array(z.string()).default([]),
  notes: z.string().nullable().optional(),

  assigned_at: z.date().default(() => new Date()),
});
